name: DeployToEC2
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    name: Deploy latest chess-club backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: "^1.13.1" # The Go version to download (if necessary) and use.

      # create cmd directory to store the built binaries
      - name: create cmd directory to store the built binaries
        run: mkdir cmd

      # build binaries
      - name: build chess-club binary
        run: go build -o cmd/chess-club

      # SSH pem file stuff
      - name: create pem file from github secret to be used to SSH into server
        run: echo '${{ secrets.ACTIONS_PRIVATE_RSA_KEY }}' >> rsa.pem

      - name: update permissions on pem file
        run: chmod 400 rsa.pem

      # restart service
      - name: remove chess-club binary leftover from previous run in server
        run: ssh -oStrictHostKeyChecking=no -i ./rsa.pem developerpipo@162.207.34.104 'rm services/chess-club || true'

      - name: upload chess-club binary
        run: sftp -oStrictHostKeyChecking=no -i ./rsa.pem developerpipo@162.207.34.104 <<< $'put ./cmd/chess-club services/.'

      - name: stop chess-club service
        run: ssh -oStrictHostKeyChecking=no -i ./rsa.pem developerpipo@162.207.34.104 'launchctl stop com.piposplace.chess-club'

      - name: unload chess-club agent (plist file)
        run: ssh -oStrictHostKeyChecking=no -i ./rsa.pem developerpipo@162.207.34.104 'launchctl unload /Users/developerpipo/Library/LaunchAgents/com.piposplace.chess-club.plist'

      - name: remove previous com.piposplace.chess-club.plist
        run: ssh -oStrictHostKeyChecking=no -i ./rsa.pem developerpipo@162.207.34.104 'rm /Users/developerpipo/Library/LaunchAgents/com.piposplace.chess-club.plist'

      - name: upload updated com.piposplace.chess-club.plist
        run: sftp -oStrictHostKeyChecking=no -i ./rsa.pem developerpipo@162.207.34.104 <<< $'put ./deploy/launchd/com.piposplace.chess-club.plist /Users/developerpipo/Library/LaunchAgents/.'

      - name: load chess-club agent (plist file)
        run: ssh -oStrictHostKeyChecking=no -i ./rsa.pem developerpipo@162.207.34.104 'launchctl load /Users/developerpipo/Library/LaunchAgents/com.piposplace.chess-club.plist'

      - name: start chess-club service
        run: ssh -oStrictHostKeyChecking=no -i ./rsa.pem developerpipo@162.207.34.104 'launchctl start com.piposplace.chess-club'
